services:
  backend:
    networks:
      - traefik-proxy
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.greatest.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.routers.greatest.entrypoints=https
      - traefik.http.services.greatest-backend.loadbalancer.server.port=80
networks:
  traefik-proxy:
    external: true
    name: traefik-proxy
