version: "3.7"
services:
  backend:
    build: .
    environment:
      - PORT=80
      - BASE_URL
      - QR_ORIGIN
    ports:
      - "${BACKEND_PORT}:80"
    secrets:
      - session-key
      - google-keys
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - db:/data/db
    restart: on-failure
  scanner:
    build: scanner
    restart: on-failure
secrets:
  session-key:
    file: session-key
  google-keys:
    file: google-keys.json
volumes:
  db:
