services:
  backend:
    networks:
      - traefik-proxy
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.greatest-http.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.routers.greatest-http.entrypoints=http
      - traefik.http.routers.greatest-http.middlewares=redirect
      - traefik.http.routers.greatest-https.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.routers.greatest-https.entrypoints=https
      - traefik.http.routers.greatest-https.tls=true
      - traefik.http.routers.greatest-https.tls.certresolver=letsencrypt
      - traefik.http.services.greatest-backend.loadbalancer.server.port=80
      - traefik.http.middlewares.redirect.redirectscheme.scheme=https
networks:
  traefik-proxy:
    external: true
    name: traefik-proxy
