env:
  node: true
extends:
  - airbnb-base
  - airbnb-typescript/base
parserOptions:
  project: ./tsconfig.json
rules:
  no-underscore-dangle:
    - error
    - allow: [ _id ]
  max-len: error
  import/prefer-default-export: off
  default-case: off
  "@typescript-eslint/switch-exhaustiveness-check": error
  consistent-return: off
overrides:
  - files:
    - src/utils/**.*
    rules:
     no-console: off
